import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./globals.css"
import Header from './header'
import { ToastContainer } from 'react-toastify'
import "react-toastify/ReactToastify.css"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

    </head>
     <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <ToastContainer/>
        </body>
    </html>
    </>
   
  )
}
